<?xml version="1.0" encoding="utf-8"?>
<Database Name="RAO_VAT" Class="RaoVatDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TIEN-PC;Initial Catalog=RAO_VAT;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="RAO_VATConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DANHMUCCHINH" Member="DANHMUCCHINHs">
    <Type Name="DANHMUCCHINH">
      <Column Name="MaDanhMucChinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMucChinh" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Thumbnail" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DANHMUCCHINH_DANHMUCCON" Member="DANHMUCCONs" ThisKey="MaDanhMucChinh" OtherKey="MaDanhMucChinh" Type="DANHMUCCON" />
    </Type>
  </Table>
  <Table Name="dbo.TINRAOVAT" Member="TINRAOVATs">
    <Type Name="TINRAOVAT">
      <Column Name="MaTinRaoVat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThoiGianDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiHanLuuTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDiaDiem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLanXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDanhMucCon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Thumbnail" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DANHMUCCON_TINRAOVAT" Member="DANHMUCCON" ThisKey="MaDanhMucCon" OtherKey="MaDanhMucCon" Type="DANHMUCCON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUCCON" Member="DANHMUCCONs">
    <Type Name="DANHMUCCON">
      <Column Name="MaDanhMucCon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMucCon" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="MaDanhMucChinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DANHMUCCON_TINRAOVAT" Member="TINRAOVATs" ThisKey="MaDanhMucCon" OtherKey="MaDanhMucCon" Type="TINRAOVAT" />
      <Association Name="DANHMUCCHINH_DANHMUCCON" Member="DANHMUCCHINH" ThisKey="MaDanhMucChinh" OtherKey="MaDanhMucChinh" Type="DANHMUCCHINH" IsForeignKey="true" />
    </Type>
  </Table>
</Database>