#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="RAO_VAT")]
	public partial class RaoVatDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDANHMUCCHINH(DANHMUCCHINH instance);
    partial void UpdateDANHMUCCHINH(DANHMUCCHINH instance);
    partial void DeleteDANHMUCCHINH(DANHMUCCHINH instance);
    partial void InsertTINRAOVAT(TINRAOVAT instance);
    partial void UpdateTINRAOVAT(TINRAOVAT instance);
    partial void DeleteTINRAOVAT(TINRAOVAT instance);
    partial void InsertDANHMUCCON(DANHMUCCON instance);
    partial void UpdateDANHMUCCON(DANHMUCCON instance);
    partial void DeleteDANHMUCCON(DANHMUCCON instance);
    #endregion
		
		public RaoVatDataClassesDataContext() : 
				base(global::DAO.Properties.Settings.Default.RAO_VATConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RaoVatDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RaoVatDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RaoVatDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RaoVatDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DANHMUCCHINH> DANHMUCCHINHs
		{
			get
			{
				return this.GetTable<DANHMUCCHINH>();
			}
		}
		
		public System.Data.Linq.Table<TINRAOVAT> TINRAOVATs
		{
			get
			{
				return this.GetTable<TINRAOVAT>();
			}
		}
		
		public System.Data.Linq.Table<DANHMUCCON> DANHMUCCONs
		{
			get
			{
				return this.GetTable<DANHMUCCON>();
			}
		}
	}
	
	[Table(Name="dbo.DANHMUCCHINH")]
	public partial class DANHMUCCHINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDanhMucChinh;
		
		private string _TenDanhMucChinh;
		
		private string _Thumbnail;
		
		private System.Nullable<bool> _Deleted;
		
		private EntitySet<DANHMUCCON> _DANHMUCCONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDanhMucChinhChanging(int value);
    partial void OnMaDanhMucChinhChanged();
    partial void OnTenDanhMucChinhChanging(string value);
    partial void OnTenDanhMucChinhChanged();
    partial void OnThumbnailChanging(string value);
    partial void OnThumbnailChanged();
    partial void OnDeletedChanging(System.Nullable<bool> value);
    partial void OnDeletedChanged();
    #endregion
		
		public DANHMUCCHINH()
		{
			this._DANHMUCCONs = new EntitySet<DANHMUCCON>(new Action<DANHMUCCON>(this.attach_DANHMUCCONs), new Action<DANHMUCCON>(this.detach_DANHMUCCONs));
			OnCreated();
		}
		
		[Column(Storage="_MaDanhMucChinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDanhMucChinh
		{
			get
			{
				return this._MaDanhMucChinh;
			}
			set
			{
				if ((this._MaDanhMucChinh != value))
				{
					this.OnMaDanhMucChinhChanging(value);
					this.SendPropertyChanging();
					this._MaDanhMucChinh = value;
					this.SendPropertyChanged("MaDanhMucChinh");
					this.OnMaDanhMucChinhChanged();
				}
			}
		}
		
		[Column(Storage="_TenDanhMucChinh", DbType="NChar(50)")]
		public string TenDanhMucChinh
		{
			get
			{
				return this._TenDanhMucChinh;
			}
			set
			{
				if ((this._TenDanhMucChinh != value))
				{
					this.OnTenDanhMucChinhChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMucChinh = value;
					this.SendPropertyChanged("TenDanhMucChinh");
					this.OnTenDanhMucChinhChanged();
				}
			}
		}
		
		[Column(Storage="_Thumbnail", DbType="VarChar(155)")]
		public string Thumbnail
		{
			get
			{
				return this._Thumbnail;
			}
			set
			{
				if ((this._Thumbnail != value))
				{
					this.OnThumbnailChanging(value);
					this.SendPropertyChanging();
					this._Thumbnail = value;
					this.SendPropertyChanged("Thumbnail");
					this.OnThumbnailChanged();
				}
			}
		}
		
		[Column(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[Association(Name="DANHMUCCHINH_DANHMUCCON", Storage="_DANHMUCCONs", ThisKey="MaDanhMucChinh", OtherKey="MaDanhMucChinh")]
		public EntitySet<DANHMUCCON> DANHMUCCONs
		{
			get
			{
				return this._DANHMUCCONs;
			}
			set
			{
				this._DANHMUCCONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHMUCCONs(DANHMUCCON entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUCCHINH = this;
		}
		
		private void detach_DANHMUCCONs(DANHMUCCON entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUCCHINH = null;
		}
	}
	
	[Table(Name="dbo.TINRAOVAT")]
	public partial class TINRAOVAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTinRaoVat;
		
		private System.Nullable<System.DateTime> _ThoiGianDang;
		
		private System.Nullable<int> _ThoiHanLuuTin;
		
		private System.Nullable<int> _MaDiaDiem;
		
		private System.Nullable<int> _SoLanXem;
		
		private System.Nullable<int> _MaNguoiDung;
		
		private System.Nullable<int> _MaDanhMucCon;
		
		private string _TieuDe;
		
		private string _Thumbnail;
		
		private System.Nullable<bool> _Deleted;
		
		private EntityRef<DANHMUCCON> _DANHMUCCON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinRaoVatChanging(int value);
    partial void OnMaTinRaoVatChanged();
    partial void OnThoiGianDangChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianDangChanged();
    partial void OnThoiHanLuuTinChanging(System.Nullable<int> value);
    partial void OnThoiHanLuuTinChanged();
    partial void OnMaDiaDiemChanging(System.Nullable<int> value);
    partial void OnMaDiaDiemChanged();
    partial void OnSoLanXemChanging(System.Nullable<int> value);
    partial void OnSoLanXemChanged();
    partial void OnMaNguoiDungChanging(System.Nullable<int> value);
    partial void OnMaNguoiDungChanged();
    partial void OnMaDanhMucConChanging(System.Nullable<int> value);
    partial void OnMaDanhMucConChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnThumbnailChanging(string value);
    partial void OnThumbnailChanged();
    partial void OnDeletedChanging(System.Nullable<bool> value);
    partial void OnDeletedChanged();
    #endregion
		
		public TINRAOVAT()
		{
			this._DANHMUCCON = default(EntityRef<DANHMUCCON>);
			OnCreated();
		}
		
		[Column(Storage="_MaTinRaoVat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTinRaoVat
		{
			get
			{
				return this._MaTinRaoVat;
			}
			set
			{
				if ((this._MaTinRaoVat != value))
				{
					this.OnMaTinRaoVatChanging(value);
					this.SendPropertyChanging();
					this._MaTinRaoVat = value;
					this.SendPropertyChanged("MaTinRaoVat");
					this.OnMaTinRaoVatChanged();
				}
			}
		}
		
		[Column(Storage="_ThoiGianDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDang
		{
			get
			{
				return this._ThoiGianDang;
			}
			set
			{
				if ((this._ThoiGianDang != value))
				{
					this.OnThoiGianDangChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianDang = value;
					this.SendPropertyChanged("ThoiGianDang");
					this.OnThoiGianDangChanged();
				}
			}
		}
		
		[Column(Storage="_ThoiHanLuuTin", DbType="Int")]
		public System.Nullable<int> ThoiHanLuuTin
		{
			get
			{
				return this._ThoiHanLuuTin;
			}
			set
			{
				if ((this._ThoiHanLuuTin != value))
				{
					this.OnThoiHanLuuTinChanging(value);
					this.SendPropertyChanging();
					this._ThoiHanLuuTin = value;
					this.SendPropertyChanged("ThoiHanLuuTin");
					this.OnThoiHanLuuTinChanged();
				}
			}
		}
		
		[Column(Storage="_MaDiaDiem", DbType="Int")]
		public System.Nullable<int> MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[Column(Storage="_SoLanXem", DbType="Int")]
		public System.Nullable<int> SoLanXem
		{
			get
			{
				return this._SoLanXem;
			}
			set
			{
				if ((this._SoLanXem != value))
				{
					this.OnSoLanXemChanging(value);
					this.SendPropertyChanging();
					this._SoLanXem = value;
					this.SendPropertyChanged("SoLanXem");
					this.OnSoLanXemChanged();
				}
			}
		}
		
		[Column(Storage="_MaNguoiDung", DbType="Int")]
		public System.Nullable<int> MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[Column(Storage="_MaDanhMucCon", DbType="Int")]
		public System.Nullable<int> MaDanhMucCon
		{
			get
			{
				return this._MaDanhMucCon;
			}
			set
			{
				if ((this._MaDanhMucCon != value))
				{
					if (this._DANHMUCCON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDanhMucConChanging(value);
					this.SendPropertyChanging();
					this._MaDanhMucCon = value;
					this.SendPropertyChanged("MaDanhMucCon");
					this.OnMaDanhMucConChanged();
				}
			}
		}
		
		[Column(Storage="_TieuDe", DbType="NChar(50)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[Column(Storage="_Thumbnail", DbType="VarChar(155)")]
		public string Thumbnail
		{
			get
			{
				return this._Thumbnail;
			}
			set
			{
				if ((this._Thumbnail != value))
				{
					this.OnThumbnailChanging(value);
					this.SendPropertyChanging();
					this._Thumbnail = value;
					this.SendPropertyChanged("Thumbnail");
					this.OnThumbnailChanged();
				}
			}
		}
		
		[Column(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[Association(Name="DANHMUCCON_TINRAOVAT", Storage="_DANHMUCCON", ThisKey="MaDanhMucCon", OtherKey="MaDanhMucCon", IsForeignKey=true)]
		public DANHMUCCON DANHMUCCON
		{
			get
			{
				return this._DANHMUCCON.Entity;
			}
			set
			{
				DANHMUCCON previousValue = this._DANHMUCCON.Entity;
				if (((previousValue != value) 
							|| (this._DANHMUCCON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANHMUCCON.Entity = null;
						previousValue.TINRAOVATs.Remove(this);
					}
					this._DANHMUCCON.Entity = value;
					if ((value != null))
					{
						value.TINRAOVATs.Add(this);
						this._MaDanhMucCon = value.MaDanhMucCon;
					}
					else
					{
						this._MaDanhMucCon = default(Nullable<int>);
					}
					this.SendPropertyChanged("DANHMUCCON");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.DANHMUCCON")]
	public partial class DANHMUCCON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDanhMucCon;
		
		private string _TenDanhMucCon;
		
		private System.Nullable<int> _MaDanhMucChinh;
		
		private System.Nullable<bool> _Deleted;
		
		private EntitySet<TINRAOVAT> _TINRAOVATs;
		
		private EntityRef<DANHMUCCHINH> _DANHMUCCHINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDanhMucConChanging(int value);
    partial void OnMaDanhMucConChanged();
    partial void OnTenDanhMucConChanging(string value);
    partial void OnTenDanhMucConChanged();
    partial void OnMaDanhMucChinhChanging(System.Nullable<int> value);
    partial void OnMaDanhMucChinhChanged();
    partial void OnDeletedChanging(System.Nullable<bool> value);
    partial void OnDeletedChanged();
    #endregion
		
		public DANHMUCCON()
		{
			this._TINRAOVATs = new EntitySet<TINRAOVAT>(new Action<TINRAOVAT>(this.attach_TINRAOVATs), new Action<TINRAOVAT>(this.detach_TINRAOVATs));
			this._DANHMUCCHINH = default(EntityRef<DANHMUCCHINH>);
			OnCreated();
		}
		
		[Column(Storage="_MaDanhMucCon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDanhMucCon
		{
			get
			{
				return this._MaDanhMucCon;
			}
			set
			{
				if ((this._MaDanhMucCon != value))
				{
					this.OnMaDanhMucConChanging(value);
					this.SendPropertyChanging();
					this._MaDanhMucCon = value;
					this.SendPropertyChanged("MaDanhMucCon");
					this.OnMaDanhMucConChanged();
				}
			}
		}
		
		[Column(Storage="_TenDanhMucCon", DbType="NChar(50)")]
		public string TenDanhMucCon
		{
			get
			{
				return this._TenDanhMucCon;
			}
			set
			{
				if ((this._TenDanhMucCon != value))
				{
					this.OnTenDanhMucConChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMucCon = value;
					this.SendPropertyChanged("TenDanhMucCon");
					this.OnTenDanhMucConChanged();
				}
			}
		}
		
		[Column(Storage="_MaDanhMucChinh", DbType="Int")]
		public System.Nullable<int> MaDanhMucChinh
		{
			get
			{
				return this._MaDanhMucChinh;
			}
			set
			{
				if ((this._MaDanhMucChinh != value))
				{
					if (this._DANHMUCCHINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDanhMucChinhChanging(value);
					this.SendPropertyChanging();
					this._MaDanhMucChinh = value;
					this.SendPropertyChanged("MaDanhMucChinh");
					this.OnMaDanhMucChinhChanged();
				}
			}
		}
		
		[Column(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[Association(Name="DANHMUCCON_TINRAOVAT", Storage="_TINRAOVATs", ThisKey="MaDanhMucCon", OtherKey="MaDanhMucCon")]
		public EntitySet<TINRAOVAT> TINRAOVATs
		{
			get
			{
				return this._TINRAOVATs;
			}
			set
			{
				this._TINRAOVATs.Assign(value);
			}
		}
		
		[Association(Name="DANHMUCCHINH_DANHMUCCON", Storage="_DANHMUCCHINH", ThisKey="MaDanhMucChinh", OtherKey="MaDanhMucChinh", IsForeignKey=true)]
		public DANHMUCCHINH DANHMUCCHINH
		{
			get
			{
				return this._DANHMUCCHINH.Entity;
			}
			set
			{
				DANHMUCCHINH previousValue = this._DANHMUCCHINH.Entity;
				if (((previousValue != value) 
							|| (this._DANHMUCCHINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANHMUCCHINH.Entity = null;
						previousValue.DANHMUCCONs.Remove(this);
					}
					this._DANHMUCCHINH.Entity = value;
					if ((value != null))
					{
						value.DANHMUCCONs.Add(this);
						this._MaDanhMucChinh = value.MaDanhMucChinh;
					}
					else
					{
						this._MaDanhMucChinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("DANHMUCCHINH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TINRAOVATs(TINRAOVAT entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUCCON = this;
		}
		
		private void detach_TINRAOVATs(TINRAOVAT entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUCCON = null;
		}
	}
}
#pragma warning restore 1591
