<?xml version="1.0" encoding="utf-8"?>
<Database Name="RAO_VAT" Class="RaoVatDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KID\SQLEE;Initial Catalog=RAO_VAT;Persist Security Info=True;User ID=sa" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="RAO_VATConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BAITRALOI" Member="BAITRALOIs">
    <Type Name="BAITRALOI">
      <Column Name="MaBaiTraLoi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTinRaoVat" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiDungTraLoi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ThoiGianTraLoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BAITRALOI_LIKED" Member="LIKEDs" ThisKey="MaBaiTraLoi,MaTinRaoVat" OtherKey="MaBaiTraLoi,MaTinRaoVat" Type="LIKED" />
      <Association Name="NGUOIDUNG_BAITRALOI" Member="NGUOIDUNG" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TREATAS" Member="TREATAs">
    <Type Name="TREATA">
      <Column Name="MaTreatAs" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TreatAsName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TREATA_MAILSERVER" Member="MAILSERVERs" ThisKey="MaTreatAs" OtherKey="MaTreatAs" Type="MAILSERVER" />
    </Type>
  </Table>
  <Table Name="dbo.BANNERGIAODIEN" Member="BANNERGIAODIENs">
    <Type Name="BANNERGIAODIEN">
      <Column Name="MaBannerGiaoDien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenBannerGiaoDien" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="DuongDanBannerGiaoDien" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="BANNERGIAODIEN_CHITIETGIAODIEN" Member="CHITIETGIAODIENs" ThisKey="MaBannerGiaoDien" OtherKey="MaBannerGiaoDien" Type="CHITIETGIAODIEN" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETGIAODIEN" Member="CHITIETGIAODIENs">
    <Type Name="CHITIETGIAODIEN">
      <Column Name="MaChiTietGiaoDien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenGiaoDien" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="MaBannerGiaoDien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLogo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTheme" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianThayDoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="BANNERGIAODIEN_CHITIETGIAODIEN" Member="BANNERGIAODIEN" ThisKey="MaBannerGiaoDien" OtherKey="MaBannerGiaoDien" Type="BANNERGIAODIEN" IsForeignKey="true" />
      <Association Name="LOGO_CHITIETGIAODIEN" Member="LOGO" ThisKey="MaLogo" OtherKey="MaLogo" Type="LOGO" IsForeignKey="true" />
      <Association Name="NGUOIDUNG_CHITIETGIAODIEN" Member="NGUOIDUNG" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="THEME_CHITIETGIAODIEN" Member="THEME" ThisKey="MaTheme" OtherKey="MaTheme" Type="THEME" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOSOTUYENDUNG" Member="CHITIETHOSOTUYENDUNGs">
    <Type Name="CHITIETHOSOTUYENDUNG">
      <Column Name="MaChiTietHoSoTuyenDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHoSoTuyenDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNganhNghe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOSOTUYENDUNG_CHITIETHOSOTUYENDUNG" Member="HOSOTUYENDUNG" ThisKey="MaHoSoTuyenDung" OtherKey="MaHoSoTuyenDung" Type="HOSOTUYENDUNG" IsForeignKey="true" />
      <Association Name="NGANHNGHE_CHITIETHOSOTUYENDUNG" Member="NGANHNGHE" ThisKey="MaNganhNghe" OtherKey="MaNganhNghe" Type="NGANHNGHE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUYENMUC" Member="CHUYENMUCs">
    <Type Name="CHUYENMUC">
      <Column Name="MaChuyenMuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChuyenMuc" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CHUYENMUC_DANHMUCCHINH" Member="DANHMUCCHINHs" ThisKey="MaChuyenMuc" OtherKey="MaChuyenMuc" Type="DANHMUCCHINH" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUCCHINH" Member="DANHMUCCHINHs">
    <Type Name="DANHMUCCHINH">
      <Column Name="MaDanhMucChinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMucChinh" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="MaChuyenMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thumbnail" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DANHMUCCHINH_DANHMUCCON" Member="DANHMUCCONs" ThisKey="MaDanhMucChinh" OtherKey="MaDanhMucChinh" Type="DANHMUCCON" />
      <Association Name="DANHMUCCHINH_EMAILNHANTINRAOVATTHEOMUCCHINH" Member="EMAILNHANTINRAOVATTHEOMUCCHINHs" ThisKey="MaDanhMucChinh" OtherKey="MaDanhMucChinh" Type="EMAILNHANTINRAOVATTHEOMUCCHINH" />
      <Association Name="CHUYENMUC_DANHMUCCHINH" Member="CHUYENMUC" ThisKey="MaChuyenMuc" OtherKey="MaChuyenMuc" Type="CHUYENMUC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUCCON" Member="DANHMUCCONs">
    <Type Name="DANHMUCCON">
      <Column Name="MaDanhMucCon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMucCon" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="MaDanhMucChinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DANHMUCCON_EMAILNHANTINRAOVATTHEOMUCCON" Member="EMAILNHANTINRAOVATTHEOMUCCONs" ThisKey="MaDanhMucCon" OtherKey="MaDanhMucCon" Type="EMAILNHANTINRAOVATTHEOMUCCON" />
      <Association Name="DANHMUCCON_TINRAOVAT" Member="TINRAOVATs" ThisKey="MaDanhMucCon" OtherKey="MaDanhMucCon" Type="TINRAOVAT" />
      <Association Name="DANHMUCCHINH_DANHMUCCON" Member="DANHMUCCHINH" ThisKey="MaDanhMucChinh" OtherKey="MaDanhMucChinh" Type="DANHMUCCHINH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIADIEM" Member="DIADIEMs">
    <Type Name="DIADIEM">
      <Column Name="MaDiaDiem" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDiaDiem" Type="System.String" DbType="NVarChar(155)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DIADIEM_TINRAOVAT" Member="TINRAOVATs" ThisKey="MaDiaDiem" OtherKey="MaDiaDiem" Type="TINRAOVAT" />
    </Type>
  </Table>
  <Table Name="dbo.EMAILNHANTINRAOVAT" Member="EMAILNHANTINRAOVATs">
    <Type Name="EMAILNHANTINRAOVAT">
      <Column Name="MaEmailNhanTinRaoVat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmailNhanTinRaoVat" Member="EmailNhanTinRaoVat1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EMAILNHANTINRAOVATTHEOMUCCHINH" Member="EMAILNHANTINRAOVATTHEOMUCCHINHs">
    <Type Name="EMAILNHANTINRAOVATTHEOMUCCHINH">
      <Column Name="MaEmailNhanTinRaoVatTheoMucChinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmailNhanTinRaoVat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaDanhMucChinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DANHMUCCHINH_EMAILNHANTINRAOVATTHEOMUCCHINH" Member="DANHMUCCHINH" ThisKey="MaDanhMucChinh" OtherKey="MaDanhMucChinh" Type="DANHMUCCHINH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EMAILNHANTINRAOVATTHEOMUCCON" Member="EMAILNHANTINRAOVATTHEOMUCCONs">
    <Type Name="EMAILNHANTINRAOVATTHEOMUCCON">
      <Column Name="MaEmailNhanTinRaoVatTheoMucCon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmailNhanTinRaoVat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaDanhMucCon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DANHMUCCON_EMAILNHANTINRAOVATTHEOMUCCON" Member="DANHMUCCON" ThisKey="MaDanhMucCon" OtherKey="MaDanhMucCon" Type="DANHMUCCON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOSOTUYENDUNG" Member="HOSOTUYENDUNGs">
    <Type Name="HOSOTUYENDUNG">
      <Column Name="MaHoSoTuyenDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTinRaoVat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DongYHienThi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangHonNhan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChiLienLac" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiDong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ThongTinHocVan" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="BangCap" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgoaiNgu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KyNang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CapBac" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoNamKinhNghiem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CongTyLamViec" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ChucDanh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TomTatKinhNghiem" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MoTaCongViecLyTuong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NguyenVong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ThoiGianLamViec" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LuongMongMuon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HOSOTUYENDUNG_CHITIETHOSOTUYENDUNG" Member="CHITIETHOSOTUYENDUNGs" ThisKey="MaHoSoTuyenDung" OtherKey="MaHoSoTuyenDung" Type="CHITIETHOSOTUYENDUNG" />
      <Association Name="TINRAOVAT_HOSOTUYENDUNG" Member="TINRAOVAT" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="TINRAOVAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LICHSUNGUOIDUNG" Member="LICHSUNGUOIDUNGs">
    <Type Name="LICHSUNGUOIDUNG">
      <Column Name="MaLichSuNguoiDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThoiGianDangNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianDangXuat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NGUOIDUNG_LICHSUNGUOIDUNG" Member="NGUOIDUNG" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LICHSUNGUOIDUNGVIPHAM" Member="LICHSUNGUOIDUNGVIPHAMs">
    <Type Name="LICHSUNGUOIDUNGVIPHAM">
      <Column Name="MaLichSuNguoiDungViPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNguoiDungViPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNguoiDungBaoCaoViPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianBaoCaoViPham" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThoiGianCanhCao" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NGUOIDUNG_LICHSUNGUOIDUNGVIPHAM" Member="NGUOIDUNG" ThisKey="MaNguoiDungViPham" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="NGUOIDUNG_LICHSUNGUOIDUNGVIPHAM1" Member="NGUOIDUNG1" ThisKey="MaNguoiDungBaoCaoViPham" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LICHSUTINRAOVATVIPHAM" Member="LICHSUTINRAOVATVIPHAMs">
    <Type Name="LICHSUTINRAOVATVIPHAM">
      <Column Name="MaLichSuTinRaoVatViPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTinRaoVatViPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNguoiDungBaoCaoViPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianBaoCaoViPham" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NGUOIDUNG_LICHSUTINRAOVATVIPHAM" Member="NGUOIDUNG" ThisKey="MaNguoiDungBaoCaoViPham" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="TINRAOVAT_LICHSUTINRAOVATVIPHAM" Member="TINRAOVAT" ThisKey="MaTinRaoVatViPham" OtherKey="MaTinRaoVat" Type="TINRAOVAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LIKED" Member="LIKEDs">
    <Type Name="LIKED">
      <Column Name="MaTinRaoVat" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLike" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianLike" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaBaiTraLoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BAITRALOI_LIKED" Member="BAITRALOI" ThisKey="MaBaiTraLoi,MaTinRaoVat" OtherKey="MaBaiTraLoi,MaTinRaoVat" Type="BAITRALOI" IsForeignKey="true" />
      <Association Name="NGUOIDUNG_LIKED" Member="NGUOIDUNG" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="TINRAOVAT_LIKED" Member="TINRAOVAT" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="TINRAOVAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAINGUOIDUNG" Member="LOAINGUOIDUNGs">
    <Type Name="LOAINGUOIDUNG">
      <Column Name="MaLoaiNguoiDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiNguoiDung" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAINGUOIDUNG_NGUOIDUNG" Member="NGUOIDUNGs" ThisKey="MaLoaiNguoiDung" OtherKey="MaLoaiNguoiDung" Type="NGUOIDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIQUANGCAO" Member="LOAIQUANGCAOs">
    <Type Name="LOAIQUANGCAO">
      <Column Name="MaLoaiQuangCao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiQuangCao" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAIQUANGCAO_QUANGCAO" Member="QUANGCAOs" ThisKey="MaLoaiQuangCao" OtherKey="MaLoaiQuangCao" Type="QUANGCAO" />
    </Type>
  </Table>
  <Table Name="dbo.LOGO" Member="LOGOs">
    <Type Name="LOGO">
      <Column Name="MaLogo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLogo" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="DuongDanLogo" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOGO_CHITIETGIAODIEN" Member="CHITIETGIAODIENs" ThisKey="MaLogo" OtherKey="MaLogo" Type="CHITIETGIAODIEN" />
    </Type>
  </Table>
  <Table Name="dbo.MAILSERVER" Member="MAILSERVERs">
    <Type Name="MAILSERVER">
      <Column Name="MaMailServer" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DomainName" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="MailServer" Member="MailServer1" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecuredAuthentication" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MaTreatAs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TREATA_MAILSERVER" Member="TREATA" ThisKey="MaTreatAs" OtherKey="MaTreatAs" Type="TREATA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGANHNGHE" Member="NGANHNGHEs">
    <Type Name="NGANHNGHE">
      <Column Name="MaNganhNghe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNganhNghe" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NGANHNGHE_CHITIETHOSOTUYENDUNG" Member="CHITIETHOSOTUYENDUNGs" ThisKey="MaNganhNghe" OtherKey="MaNganhNghe" Type="CHITIETHOSOTUYENDUNG" />
      <Association Name="NGANHNGHE_TINTUYENDUNG" Member="TINTUYENDUNGs" ThisKey="MaNganhNghe" OtherKey="MaNganhNghe" Type="TINTUYENDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG" Member="NGUOIDUNGs">
    <Type Name="NGUOIDUNG">
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNguoiDung" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaKichHoatTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangKichHoatTaiKhoan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaLoaiNguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NGUOIDUNG_BAITRALOI" Member="BAITRALOIs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="BAITRALOI" />
      <Association Name="NGUOIDUNG_CHITIETGIAODIEN" Member="CHITIETGIAODIENs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="CHITIETGIAODIEN" />
      <Association Name="NGUOIDUNG_LICHSUNGUOIDUNG" Member="LICHSUNGUOIDUNGs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="LICHSUNGUOIDUNG" />
      <Association Name="NGUOIDUNG_LICHSUNGUOIDUNGVIPHAM" Member="LICHSUNGUOIDUNGVIPHAMs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDungViPham" Type="LICHSUNGUOIDUNGVIPHAM" />
      <Association Name="NGUOIDUNG_LICHSUNGUOIDUNGVIPHAM1" Member="LICHSUNGUOIDUNGVIPHAMs1" ThisKey="MaNguoiDung" OtherKey="MaNguoiDungBaoCaoViPham" Type="LICHSUNGUOIDUNGVIPHAM" />
      <Association Name="NGUOIDUNG_LICHSUTINRAOVATVIPHAM" Member="LICHSUTINRAOVATVIPHAMs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDungBaoCaoViPham" Type="LICHSUTINRAOVATVIPHAM" />
      <Association Name="NGUOIDUNG_LIKED" Member="LIKEDs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="LIKED" />
      <Association Name="NGUOIDUNG_QUANGCAO" Member="QUANGCAOs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="QUANGCAO" />
      <Association Name="NGUOIDUNG_TINNHAN" Member="TINNHANs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="TINNHAN" />
      <Association Name="NGUOIDUNG_TINNHAN1" Member="TINNHANs1" ThisKey="MaNguoiDung" OtherKey="MaNguoiNhanTin" Type="TINNHAN" />
      <Association Name="NGUOIDUNG_TINRAOVAT" Member="TINRAOVATs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="TINRAOVAT" />
      <Association Name="NGUOIDUNG_TINRAOVATDALUU" Member="TINRAOVATDALUUs" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="TINRAOVATDALUU" />
      <Association Name="LOAINGUOIDUNG_NGUOIDUNG" Member="LOAINGUOIDUNG" ThisKey="MaLoaiNguoiDung" OtherKey="MaLoaiNguoiDung" Type="LOAINGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUANGCAO" Member="QUANGCAOs">
    <Type Name="QUANGCAO">
      <Column Name="MaQuangCao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenQuangCao" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Column Name="ThoiGianDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NoiDungQuangCao" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaLoaiQuangCao" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOAIQUANGCAO_QUANGCAO" Member="LOAIQUANGCAO" ThisKey="MaLoaiQuangCao" OtherKey="MaLoaiQuangCao" Type="LOAIQUANGCAO" IsForeignKey="true" />
      <Association Name="NGUOIDUNG_QUANGCAO" Member="NGUOIDUNG" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THEME" Member="THEMEs">
    <Type Name="THEME">
      <Column Name="MaTheme" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTheme" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="Background" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="Border" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="CSS" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="THEME_CHITIETGIAODIEN" Member="CHITIETGIAODIENs" ThisKey="MaTheme" OtherKey="MaTheme" Type="CHITIETGIAODIEN" />
    </Type>
  </Table>
  <Table Name="dbo.TINNHAN" Member="TINNHANs">
    <Type Name="TINNHAN">
      <Column Name="MaTinNhan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNguoiNhanTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuDeTinNhan" Type="System.String" DbType="NVarChar(155)" CanBeNull="true" />
      <Column Name="NoiDungTinNhan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ThoiGianNhanTin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Readed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NGUOIDUNG_TINNHAN" Member="NGUOIDUNG" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="NGUOIDUNG_TINNHAN1" Member="NGUOIDUNG1" ThisKey="MaNguoiNhanTin" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TINRAOVAT" Member="TINRAOVATs">
    <Type Name="TINRAOVAT">
      <Column Name="MaTinRaoVat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThoiGianDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiHanLuuTin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDiaDiem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLanXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDanhMucCon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Thumbnail" Type="System.String" DbType="VarChar(155)" CanBeNull="true" />
      <Column Name="GhiChuHinhAnh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TINRAOVAT_HOSOTUYENDUNG" Member="HOSOTUYENDUNGs" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="HOSOTUYENDUNG" />
      <Association Name="TINRAOVAT_LICHSUTINRAOVATVIPHAM" Member="LICHSUTINRAOVATVIPHAMs" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVatViPham" Type="LICHSUTINRAOVATVIPHAM" />
      <Association Name="TINRAOVAT_LIKED" Member="LIKEDs" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="LIKED" />
      <Association Name="TINRAOVAT_TINRAOVATBATDONGSAN" Member="TINRAOVATBATDONGSANs" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="TINRAOVATBATDONGSAN" />
      <Association Name="TINRAOVAT_TINRAOVATDALUU" Member="TINRAOVATDALUUs" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="TINRAOVATDALUU" />
      <Association Name="TINRAOVAT_TINRAOVATTHUONG" Member="TINRAOVATTHUONGs" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="TINRAOVATTHUONG" />
      <Association Name="TINRAOVAT_TINTUYENDUNG" Member="TINTUYENDUNGs" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="TINTUYENDUNG" />
      <Association Name="DANHMUCCON_TINRAOVAT" Member="DANHMUCCON" ThisKey="MaDanhMucCon" OtherKey="MaDanhMucCon" Type="DANHMUCCON" IsForeignKey="true" />
      <Association Name="DIADIEM_TINRAOVAT" Member="DIADIEM" ThisKey="MaDiaDiem" OtherKey="MaDiaDiem" Type="DIADIEM" IsForeignKey="true" />
      <Association Name="NGUOIDUNG_TINRAOVAT" Member="NGUOIDUNG" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TINRAOVATBATDONGSAN" Member="TINRAOVATBATDONGSANs">
    <Type Name="TINRAOVATBATDONGSAN">
      <Column Name="MaTinRaoVatBatDongSan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTinRaoVat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoiDungTinRaoVat" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="DienTich" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Huong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LoGioi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MatTien" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GiayTo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DuongTruocNha" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienNhaNuoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NuocMay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoPhongNgu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoNhaVeSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NamXayDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhongKhach" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GaraOto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NhaBep" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HoBoi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SanThuong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DieuHoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SanVuon" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThangMay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GanTruongMauGiao" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GanTruongCap1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GanTruongCap2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GanTruongCap3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GanCho" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GanBenhVien" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GanTrungTamThuongMai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GanTrungTamGiaiTri" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GanCongVien" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TINRAOVAT_TINRAOVATBATDONGSAN" Member="TINRAOVAT" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="TINRAOVAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TINRAOVATDALUU" Member="TINRAOVATDALUUs">
    <Type Name="TINRAOVATDALUU">
      <Column Name="MaTinRaoVatDaLuu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTinRaoVat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianLuu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NGUOIDUNG_TINRAOVATDALUU" Member="NGUOIDUNG" ThisKey="MaNguoiDung" OtherKey="MaNguoiDung" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="TINRAOVAT_TINRAOVATDALUU" Member="TINRAOVAT" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="TINRAOVAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TINRAOVATTHUONG" Member="TINRAOVATTHUONGs">
    <Type Name="TINRAOVATTHUONG">
      <Column Name="MaTinRaoVatThuong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTinRaoVat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoiDungTinRaoVat" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TINRAOVAT_TINRAOVATTHUONG" Member="TINRAOVAT" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="TINRAOVAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TINTUYENDUNG" Member="TINTUYENDUNGs">
    <Type Name="TINTUYENDUNG">
      <Column Name="MaTinTuyenDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTinRaoVat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenNhaTuyenDung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiThieuNhaTuyenDung" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NguoiDaiDien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChiLienHe" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaNganhNghe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViTriTuyenDung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="YeuCauCongViec" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="YeuCauKinhNghiem" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ThoiGianLamViec" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoLuongCanTuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MucLuongKhoiDiem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianThuViec" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LuongThuViec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuyenLoiDuocHuong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HoSoBaoGom" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ThoiHanKetThucNopHoSo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NGANHNGHE_TINTUYENDUNG" Member="NGANHNGHE" ThisKey="MaNganhNghe" OtherKey="MaNganhNghe" Type="NGANHNGHE" IsForeignKey="true" />
      <Association Name="TINRAOVAT_TINTUYENDUNG" Member="TINRAOVAT" ThisKey="MaTinRaoVat" OtherKey="MaTinRaoVat" Type="TINRAOVAT" IsForeignKey="true" />
    </Type>
  </Table>
</Database>